# Generated by Django 5.1 on 2024-09-04 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_interest_subject_educatorprofile_experience_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='educatorprofile',
            name='banner_image',
            field=models.ImageField(default='banner_images/default.png', upload_to='banner_images'),
        ),
        migrations.AddField(
            model_name='educatorprofile',
            name='profile_image',
            field=models.ImageField(default='profile_images/default.png', upload_to='profile_images'),
        ),
        migrations.AddField(
            model_name='learnerprofile',
            name='banner_image',
            field=models.ImageField(default='banner_images/default.png', upload_to='banner_images'),
        ),
        migrations.AddField(
            model_name='learnerprofile',
            name='profile_image',
            field=models.ImageField(default='profile_images/default.png', upload_to='profile_images'),
        ),
    ]
