# Generated by Django 5.1 on 2024-09-05 17:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_educatorprofile_banner_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='educatorprofile',
            name='banner_image',
            field=models.ImageField(default='banner_images/default_profile.jpg', upload_to='banner_images'),
        ),
        migrations.AlterField(
            model_name='educatorprofile',
            name='profile_image',
            field=models.ImageField(default='profile_images/default_profile.jpg', upload_to='profile_images'),
        ),
        migrations.AlterField(
            model_name='learnerprofile',
            name='banner_image',
            field=models.ImageField(default='banner_images/default_profile.jpg', upload_to='banner_images'),
        ),
        migrations.AlterField(
            model_name='learnerprofile',
            name='profile_image',
            field=models.ImageField(default='profile_images/default_profile.jpg', upload_to='profile_images'),
        ),
        migrations.CreateModel(
            name='Classroom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('educator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.educatorprofile')),
                ('student', models.ManyToManyField(blank=True, to='accounts.learnerprofile')),
            ],
        ),
    ]
