# Generated by Django 5.1 on 2024-09-05 18:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_educatorprofile_banner_image_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Classroom',
        ),
    ]
