# Generated by Django 5.1 on 2024-09-10 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_educatorprofile_banner_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='educatorprofile',
            name='banner_image',
            field=models.ImageField(default='banner_images/banner_d.jpg', upload_to='banner_images'),
        ),
        migrations.AlterField(
            model_name='educatorprofile',
            name='profile_image',
            field=models.ImageField(default='profile_images/profile_d.jpg', upload_to='profile_images'),
        ),
    ]
