# Generated by Django 5.1 on 2024-09-10 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_educatorprofile_banner_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='educatorprofile',
            name='profile_image',
            field=models.ImageField(default='profile_images/profile_d.png', upload_to='profile_images'),
        ),
        migrations.AlterField(
            model_name='learnerprofile',
            name='profile_image',
            field=models.ImageField(default='profile_images/profile_d.png', upload_to='profile_images'),
        ),
    ]
