# Generated by Django 5.1 on 2024-09-10 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_alter_educatorprofile_profile_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='educatorprofile',
            name='best_describe',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='educatorprofile',
            name='bio',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='educatorprofile',
            name='location',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='educatorprofile',
            name='phone',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AddField(
            model_name='educatorprofile',
            name='website',
            field=models.URLField(blank=True, null=True),
        ),
    ]
