# Generated by Django 5.1 on 2024-09-10 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_educatorprofile_best_describe_educatorprofile_bio_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='educatorprofile',
            name='qualification',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
