# Generated by Django 5.1 on 2024-09-10 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_alter_educatorprofile_qualification'),
    ]

    operations = [
        migrations.AddField(
            model_name='learnerprofile',
            name='best_describe',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='learnerprofile',
            name='bio',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='learnerprofile',
            name='github_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='learnerprofile',
            name='linkedin_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='learnerprofile',
            name='phone',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AddField(
            model_name='learnerprofile',
            name='website',
            field=models.URLField(blank=True, null=True),
        ),
    ]
