# Generated by Django 5.1 on 2024-09-16 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_learnerprofile_best_describe_learnerprofile_bio_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='educatorprofile',
            name='banner_image',
            field=models.ImageField(default='banner_images/banner.webp', upload_to='banner_images'),
        ),
        migrations.AlterField(
            model_name='educatorprofile',
            name='profile_image',
            field=models.ImageField(default='profile_images/profile.webp', upload_to='profile_images'),
        ),
        migrations.AlterField(
            model_name='learnerprofile',
            name='banner_image',
            field=models.ImageField(default='banner_images/banner.webp', upload_to='banner_images'),
        ),
        migrations.AlterField(
            model_name='learnerprofile',
            name='profile_image',
            field=models.ImageField(default='profile_images/profile.webp', upload_to='profile_images'),
        ),
    ]
