# Generated by Django 5.1 on 2024-09-18 19:45

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_alter_educatorprofile_banner_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='educatorprofile',
            name='banner_image',
            field=cloudinary.models.CloudinaryField(default='banner_images/banner.webp', max_length=255, verbose_name='banner_image'),
        ),
        migrations.AlterField(
            model_name='educatorprofile',
            name='profile_image',
            field=cloudinary.models.CloudinaryField(default='profile_images/profile.webp', max_length=255, verbose_name='profile_image'),
        ),
        migrations.AlterField(
            model_name='learnerprofile',
            name='banner_image',
            field=cloudinary.models.CloudinaryField(default='banner_images/banner.webp', max_length=255, verbose_name='banner_image'),
        ),
        migrations.AlterField(
            model_name='learnerprofile',
            name='profile_image',
            field=cloudinary.models.CloudinaryField(default='profile_images/profile.webp', max_length=255, verbose_name='profile_image'),
        ),
    ]
