# Generated by Django 5.1 on 2024-09-19 22:07

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_alter_educatorprofile_banner_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='educatorprofile',
            name='banner_image',
            field=cloudinary.models.CloudinaryField(default='https://asset.cloudinary.com/dzchm8yml/5e440e639457b254424905a68c5f6ae5', max_length=255, verbose_name='banner_image'),
        ),
        migrations.AlterField(
            model_name='educatorprofile',
            name='profile_image',
            field=cloudinary.models.CloudinaryField(default='https://asset.cloudinary.com/dzchm8yml/83d155750bbced298449b5a3064d9f72', max_length=255, verbose_name='profile_image'),
        ),
    ]
