# Generated by Django 5.1 on 2024-09-05 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learn', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classroom',
            name='room_code',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
