# Generated by Django 5.1 on 2024-09-05 19:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_delete_classroom'),
        ('learn', '0002_alter_classroom_room_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classroom',
            name='educator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.educatorprofile'),
        ),
    ]
