# Generated by Django 5.1 on 2024-09-08 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learn', '0004_classroom_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='classroom',
            name='status',
            field=models.CharField(choices=[('public', 'Public'), ('private', 'Private')], default='public', max_length=10),
        ),
    ]
