# Generated by Django 5.1 on 2024-09-10 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learn', '0005_classroom_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='classroom',
            name='topic',
            field=models.CharField(default='other', max_length=250),
        ),
    ]
