# Generated by Django 5.1 on 2024-09-12 15:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_learnerprofile_best_describe_learnerprofile_bio_and_more'),
        ('learn', '0007_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classroom',
            name='educator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='classrooms', to='accounts.educatorprofile'),
        ),
    ]
