# Generated by Django 5.1 on 2024-09-12 15:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learn', '0009_alerts_notes_classroom_alerts_classroom_notes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classroom',
            name='alerts',
        ),
        migrations.RemoveField(
            model_name='classroom',
            name='notes',
        ),
        migrations.AddField(
            model_name='alerts',
            name='classroom',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='learn.classroom'),
        ),
        migrations.AddField(
            model_name='notes',
            name='classroom',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='learn.classroom'),
        ),
    ]
