# Generated by Django 5.1 on 2024-09-12 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learn', '0010_remove_classroom_alerts_remove_classroom_notes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='alerts',
            name='name',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='notes',
            name='name',
            field=models.CharField(default='', max_length=255),
        ),
    ]
