# Generated by Django 5.1 on 2024-09-13 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learn', '0013_rename_user2_personalmessage_receiver_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='personalmessage',
            name='url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
