# Generated by Django 5.1 on 2024-09-26 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0018_alter_learnerprofile_banner_image_and_more'),
        ('learn', '0017_requests'),
    ]

    operations = [
        migrations.AddField(
            model_name='classroom',
            name='additional_educators',
            field=models.ManyToManyField(blank=True, related_name='joined_classrooms', to='accounts.educatorprofile'),
        ),
    ]
